export const INIT_QUESTIONS = 'INIT_QUESTIONS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PARSED_PRODUCTS = 'GET_PARSED_PRODUCTS';
export const UPDATE_QUESTIONS = 'UPDATE_QUESTIONS';
